# Generated by Django 3.0.3 on 2020-05-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('k_numaccidente', models.IntegerField(primary_key=True, serialize=False)),
                ('w_ntsbdoc', models.CharField(blank=True, max_length=100, null=True)),
                ('d_conclusion', models.CharField(max_length=500)),
                ('n_heridos', models.IntegerField()),
                ('n_muertos', models.IntegerField()),
            ],
            options={
                'db_table': 'accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('k_nommodelo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('d_general', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'avion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('k_nomentidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('f_fundacion', models.DateField(blank=True, null=True)),
                ('s_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('k_nomfabricante', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('f_fundacion', models.DateField(blank=True, null=True)),
                ('u_headquarter', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('k_num', models.IntegerField(primary_key=True, serialize=False)),
                ('un_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('un_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('u_nomlugar', models.CharField(blank=True, max_length=30, null=True)),
                ('f_hora', models.DateTimeField()),
                ('d_situacion', models.CharField(max_length=200)),
                ('un_altitud', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'situacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('k_nomvuelo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_salida', models.DateTimeField()),
                ('u_ciudadorigen', models.CharField(max_length=50)),
                ('u_ciudaddestino', models.CharField(blank=True, max_length=50, null=True)),
                ('i_registroavion', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'vuelo',
                'managed': False,
            },
        ),
    ]
