/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 22-Feb-2020 4:33:33 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS Accidente CASCADE
;

DROP TABLE IF EXISTS Avion CASCADE
;

DROP TABLE IF EXISTS Entidad CASCADE
;

DROP TABLE IF EXISTS Fabricante CASCADE
;

DROP TABLE IF EXISTS Situacion CASCADE
;

DROP TABLE IF EXISTS Vuelo CASCADE
;

/* Create Tables */

CREATE TABLE Accidente
(
	k_numaccidente serial NOT NULL,
	w_ntsbdoc varchar(100) NULL,
	"d_conclusion" varchar(500) NOT NULL,
	n_heridos numeric NULL,
	n_muertos numeric NULL
)
;

CREATE TABLE Avion
(
	k_nommodelo varchar(50) NOT NULL,
	d_general varchar(200) NULL,
	k_nomfabricante varchar(50) NULL
)
;

CREATE TABLE Entidad
(
	k_nomentidad varchar(50) NOT NULL,
	f_fundacion date NULL,
	s_tipo varchar(50) NOT NULL
)
;

CREATE TABLE Fabricante
(
	k_nomfabricante varchar(50) NOT NULL,
	f_fundacion date NULL,
	u_headquarter varchar(50) NULL
)
;

CREATE TABLE Situacion
(
	k_num integer NOT NULL,
	un_lat numeric(8,6) NOT NULL,
	un_lon numeric(9,6) NOT NULL,
	u_nomlugar varchar(30) NULL,
	f_hora timestamp with time zone NOT NULL,
	"d_situacion" varchar(200) NOT NULL,
	iframe_osm varchar(200) NOT NULL,
	un_altitud integer NULL,
	k_numaccidente serial NOT NULL
)
;

CREATE TABLE Vuelo
(
	k_nomvuelo varchar(10) NOT NULL,
	f_salida timestamp with time zone NOT NULL,
	u_ciudadorigen varchar(50) NOT NULL,
	u_ciudaddestino varchar(50) NULL,
	"i_registroavion" varchar(6) NOT NULL,
	k_nomentidad varchar(50) NULL,
	k_nommodelo varchar(50) NULL,
	k_numaccidente serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Accidente ADD CONSTRAINT PK_numaccidente
	PRIMARY KEY (k_numaccidente)
;

ALTER TABLE Accidente ADD CONSTRAINT CHK_heridosmayorcero CHECK (n_heridos >= 0)
;

ALTER TABLE Accidente ADD CONSTRAINT CHK_muertosmayorcero CHECK (n_muertos >= 0)
;

ALTER TABLE Avion ADD CONSTRAINT PK_nommodelo
	PRIMARY KEY (k_nommodelo)
;

ALTER TABLE Entidad ADD CONSTRAINT PK_nomentidad
	PRIMARY KEY (k_nomentidad)
;

ALTER TABLE Entidad ADD CONSTRAINT CHK_tipoentidad CHECK (s_tipo in ('Militar','Comercial','Privado'))
;

ALTER TABLE Fabricante ADD CONSTRAINT PK_nomfabricante
	PRIMARY KEY (k_nomfabricante)
;

ALTER TABLE Situacion ADD CONSTRAINT PK_num
	PRIMARY KEY (k_num,k_numaccidente)
;

ALTER TABLE Situacion ADD CONSTRAINT CHK_latitud CHECK (un_lat <= 90 AND un_lat >= -90)
;

ALTER TABLE Situacion ADD CONSTRAINT CHK_longitud CHECK (un_lon <= 180 AND un_lon >= -180)
;

ALTER TABLE Vuelo ADD CONSTRAINT PK_Vuelo
	PRIMARY KEY (k_nomvuelo,f_salida)
;

/* Create Foreign Key Constraints */

ALTER TABLE Avion ADD CONSTRAINT FK_Avion_Fabricante
	FOREIGN KEY (k_nomfabricante) REFERENCES Fabricante (k_nomfabricante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Situacion ADD CONSTRAINT FK_Situacion_Accidente
	FOREIGN KEY (k_numaccidente) REFERENCES Accidente (k_numaccidente) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE Vuelo ADD CONSTRAINT FK_Vuelo_Accidente
	FOREIGN KEY (k_numaccidente) REFERENCES Accidente (k_numaccidente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Vuelo ADD CONSTRAINT FK_Vuelo_Avion
	FOREIGN KEY (k_nommodelo) REFERENCES Avion (k_nommodelo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Vuelo ADD CONSTRAINT FK_Vuelo_Entidad
	FOREIGN KEY (k_nomentidad) REFERENCES Entidad (k_nomentidad) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 
